steps:
  # Build Backend Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA', './backend']
    id: 'build-backend'
  
  # Build Frontend Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA', './Frontend']
    id: 'build-frontend'
  
  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA']
    waitFor: ['build-backend']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA']
    waitFor: ['build-frontend']
  
  # Deploy Backend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
  
  # Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe backend-service --region europe-west1 --format 'value(status.url)')
        gcloud run deploy frontend-service \
          --image gcr.io/$PROJECT_ID/frontend:$COMMIT_SHA \
          --region europe-west1 \
          --allow-unauthenticated \
          --port 80 \
          --set-env-vars REACT_APP_BACKEND_URL=$BACKEND_URL

timeout: '1200s'
